version: '3.8'

services:
  # MongoDB 主資料庫
  mongodb:
    image: mongo:7.0
    container_name: localite-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: localite
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - localite-network

  # MySQL 交易資料庫
  mysql:
    image: mysql:8.0
    container_name: localite-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: localite
      MYSQL_USER: localite
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - localite-network

  # Redis 快取
  redis:
    image: redis:7.2-alpine
    container_name: localite-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - localite-network

  # Redis Commander (Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: localite-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - localite-network
    depends_on:
      - redis

  # phpMyAdmin (MySQL GUI)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: localite-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - localite-network
    depends_on:
      - mysql

  # Mongo Express (MongoDB GUI)
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: localite-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    ports:
      - "8082:8081"
    networks:
      - localite-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  localite-network:
    driver: bridge 